- name: Bonding and White Filling
  summary: |
    <p>Bonding is a popular method to enhance the aesthetics of your smile. Bonding can be used to correct cracks or gaps in teeth, as a filling after a cavity has been removed, or to cover up stains or discolored teeth.</p>
  detail: |
    <p>Bonding is a popular method to enhance the aesthetics of your smile. Bonding can be used to correct cracks or gaps in teeth, as a filling after a cavity has been removed, or to cover up stains or discolored teeth.</p>
    <p>A composite resin is used on the affected tooth or teeth. It is molded and sculpted over an adhsive gel that is placed on the tooth. After the resin has been applied an ultraviolet light is used to harden the resin, which is then polished to give you a fresh, new smile.</p>
    <p>Bonding is an obvious improvement over unsightly silver amalgam fillings. With the advancements in dental technology, bonding usually lasts for over 10 years. It is a safe, affordable, and attractive solution for many dental problems.</p>

- name: Bridges
  summary: |
    <p>Dental bridges are a great way to replace missing teeth. Your existing teeth are used to literally create a bridge to cross the area where your tooth is missing. Bridges are made from gold, metal, alloys, or porcelain to ensure that they are strong and durable.</p>

- name: Crowns
  summary: |
    <p>Crowns can be made from porcelain, porcelain fused to metal, or a full gold crown. To maintain a natural look and feel a porcelain finished crown is best, as it can be matched to the shade of your other teeth. This will allow it to blend in and appear just like one of your natural teeth.</p>

- name: Crown Lengthening
  summary: |
    <p>Crown Lengthening is done for restorative dentistry and to improve the esthetics of your gum line. This procedure adjusts the gum and bone level to expose more of the tooth so it can be restored. Sometimes crown lengthening is done to improve a "gummy" smile because the teeth appear short.</p>

- name: Veneers
  summary: |
    <p>Veneers are an excellent way to redesign and reshape your entire mouth. Veneers are a very thin ceramic shell that covers your existing tooth structure. In placing these new veneers on your teeth, you are able to fix the look of issues such as staining, cracked teeth, spaces, misaligned teeth, chipped teeth and many other issues.</p>

- name: Dental Implants
  summary: |
    <p>Now patients who are missing teeth have a strong, beautiful alternative to bridges, partials, or full dentures. Dental implants will improve your smile and your lifestyle. They look, feel, and function like natural teeth because of a titanium anchor attached to the jawbone. Implants can also anchor bridges, partials, or full dentures to eliminate slipping.</p>

- name: "Dental Hygiene"
  summary: |
    <p>While at our office, we make sure you receive the highest level of service and ensure our dental work is of the highest quality. To ensure you maintain great oral health, your personal oral hygiene routine needs this same level of quality. We help you establish a dental hygiene routine to keep your teeth healthy and white.</p>

- name: Oral Cancer Screenings
  summary: |
    <p>Oral cancer screenings are a very important part of a dental visit. With advances in modern technology, we are now able to pinpoint the start of a potential problem much earlier in its evolution. The ability to do so is extremely important in being able to treat any concerns prior to their becoming a major irreversible problem.</p>

- name: Root Planing
  summary: |
    <p>Often there is plaque and tartar that accumulates below the gum line. In this scenario, we will clean and smooth this area with special instruments to ensure that the area is completely spotless.</p>

- name: Whitening and Bleaching
  summary: |
    <p>Keeping our teeth their whitest is a lot harder than it sounds. Teeth whitening is an excellent way to restore the natural color of your teeth, or even make them whiter if you desire.</p>

